# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera_type',
            field=models.CharField(choices=[('IPHONE', 'iPhone'), ('NIKON', 'Nikon'), ('CANNON', 'Cannon'), ('OTHER', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='type_of_photography',
            field=models.CharField(choices=[('NATURE', 'Nature'), ('URBAN', 'Urban'), ('PORTRAIT', 'Portrait'), ('OTHER', 'Other')], max_length=144),
        ),
    ]
