# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170117_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='type_of_photography',
            field=models.CharField(choices=[('NATURE', 'Nature'), ('URBAN', 'Urban'), ('PORTRAIT', 'Portrait'), ('OTHER', 'Other')], max_length=144, null=True),
        ),
    ]
