# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 02:02
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['date_uploaded']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['date_uploaded']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=''),
        ),
    ]
