# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20170123_1910'),
        ('imager_images', '0002_auto_20170123_1835'),
    ]

    operations = [
    ]
