# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20170118_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='albums', to='imager_images.Photo'),
        ),
    ]
