# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20170206_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
